// <auto-generated />
using System;
using FlowerShop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FlowerShop.Data.Migrations
{
    [DbContext(typeof(FlowerDbContext))]
    [Migration("20260313213002_NewDb")]
    partial class NewDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FlowerShop.Data.Models.BouquetEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<float>("Rating")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Bouquets", null, t =>
                        {
                            t.HasCheckConstraint("CK_Bouquets_Price_NonNegative", "\"Price\" >= 0");

                            t.HasCheckConstraint("CK_Bouquets_Quantity_NonNegative", "\"Quantity\" >= 0");
                        });
                });

            modelBuilder.Entity("FlowerShop.Data.Models.CartEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("FlowerShop.Data.Models.CartItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BouquetId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CartId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PriceSnapshot")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SoftToyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BouquetId");

                    b.HasIndex("CartId");

                    b.HasIndex("SoftToyId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("FlowerShop.Data.Models.FeedbackEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<float>("StoreRating")
                        .HasColumnType("real");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("FlowerShop.Data.Models.FeedbackItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BouquetId")
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("FeedbackId")
                        .HasColumnType("uuid");

                    b.Property<int>("ProductRating")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SoftToyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BouquetId");

                    b.HasIndex("FeedbackId");

                    b.HasIndex("SoftToyId");

                    b.ToTable("FeedbackItems");
                });

            modelBuilder.Entity("FlowerShop.Data.Models.OrderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("CanReview")
                        .HasColumnType("boolean");

                    b.Property<string>("DeliveryAddress")
                        .HasColumnType("text");

                    b.Property<DateTime>("PickupDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("FlowerShop.Data.Models.OrderItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BouquetId")
                        .HasColumnType("uuid");

                    b.Property<string>("ImageUrlSnapshot")
                        .HasColumnType("text");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SoftToyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BouquetId");

                    b.HasIndex("OrderId");

                    b.HasIndex("SoftToyId");

                    b.ToTable("OrderItems", (string)null);
                });

            modelBuilder.Entity("FlowerShop.Data.Models.SoftToyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<float>("Rating")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("SoftToys");
                });

            modelBuilder.Entity("FlowerShop.Data.Models.UserDomain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CodeOrder")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("DateRegistration")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("FlowerShop.Data.Models.CartEntity", b =>
                {
                    b.HasOne("FlowerShop.Data.Models.UserDomain", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FlowerShop.Data.Models.CartItemEntity", b =>
                {
                    b.HasOne("FlowerShop.Data.Models.BouquetEntity", "Bouquet")
                        .WithMany()
                        .HasForeignKey("BouquetId");

                    b.HasOne("FlowerShop.Data.Models.CartEntity", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlowerShop.Data.Models.SoftToyEntity", "SoftToy")
                        .WithMany()
                        .HasForeignKey("SoftToyId");

                    b.Navigation("Bouquet");

                    b.Navigation("Cart");

                    b.Navigation("SoftToy");
                });

            modelBuilder.Entity("FlowerShop.Data.Models.FeedbackEntity", b =>
                {
                    b.HasOne("FlowerShop.Data.Models.UserDomain", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FlowerShop.Data.Models.FeedbackItemEntity", b =>
                {
                    b.HasOne("FlowerShop.Data.Models.BouquetEntity", "Bouquet")
                        .WithMany()
                        .HasForeignKey("BouquetId");

                    b.HasOne("FlowerShop.Data.Models.FeedbackEntity", "Feedback")
                        .WithMany("FeedbackItems")
                        .HasForeignKey("FeedbackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlowerShop.Data.Models.SoftToyEntity", "SoftToy")
                        .WithMany()
                        .HasForeignKey("SoftToyId");

                    b.Navigation("Bouquet");

                    b.Navigation("Feedback");

                    b.Navigation("SoftToy");
                });

            modelBuilder.Entity("FlowerShop.Data.Models.OrderEntity", b =>
                {
                    b.HasOne("FlowerShop.Data.Models.UserDomain", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FlowerShop.Data.Models.OrderItemEntity", b =>
                {
                    b.HasOne("FlowerShop.Data.Models.BouquetEntity", "Bouquet")
                        .WithMany()
                        .HasForeignKey("BouquetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FlowerShop.Data.Models.OrderEntity", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlowerShop.Data.Models.SoftToyEntity", "SoftToy")
                        .WithMany()
                        .HasForeignKey("SoftToyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Bouquet");

                    b.Navigation("Order");

                    b.Navigation("SoftToy");
                });

            modelBuilder.Entity("FlowerShop.Data.Models.CartEntity", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("FlowerShop.Data.Models.FeedbackEntity", b =>
                {
                    b.Navigation("FeedbackItems");
                });

            modelBuilder.Entity("FlowerShop.Data.Models.OrderEntity", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("FlowerShop.Data.Models.UserDomain", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
